import {
  Sparkles,
  Flower,
  Sofa,
  ShoppingCart,
  Smartphone,
  Laptop,
  Home,
  Droplet,
  Shirt,
  Footprints,
  Watch,
  Glasses,
  Car,
  Bike,
  Lightbulb,
} from 'lucide-angular';

export const CATEGORY_ICONS: Record<string, any> = {
  beauty: Sparkles,
  fragrances: Flower,
  furniture: Sofa,
  groceries: ShoppingCart,
  smartphones: Smartphone,
  laptops: Laptop,
  'home-decoration': Home,
  skincare: Droplet,
  'mens-shirts': Shirt,
  'mens-shoes': Footprints,
  'womens-dresses': Shirt,
  'womens-shoes': Footprints,
  'mens-watches': Watch,
  'womens-watches': Watch,
  sunglasses: Glasses,
  automotive: Car,
  motorcycle: Bike,
  lighting: Lightbulb,
};
